// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _xor_bit_HH_
#define _xor_bit_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct xor_bit : public sc_module {
    // Port declarations 8
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<4> > in1;
    sc_in< sc_lv<4> > in2;
    sc_out< sc_lv<4> > out_r;
    sc_out< sc_logic > out_r_ap_vld;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    xor_bit(sc_module_name name);
    SC_HAS_PROCESS(xor_bit);

    ~xor_bit();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_out_r();
    void thread_out_r_ap_vld();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
