set_max_delay -from [all_inputs] -to [all_outputs] 10.000




set_property PACKAGE_PIN N17 [get_ports ap_done]
set_property PACKAGE_PIN W19 [get_ports ap_idle]
set_property PACKAGE_PIN W18 [get_ports ap_ready]
set_property IOSTANDARD LVCMOS33 [get_ports ap_done]
set_property IOSTANDARD LVCMOS33 [get_ports ap_idle]
set_property PACKAGE_PIN T16 [get_ports {in1[3]}]
set_property PACKAGE_PIN W13 [get_ports {in1[2]}]
set_property PACKAGE_PIN P15 [get_ports {in1[1]}]
set_property PACKAGE_PIN G15 [get_ports {in1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in1[0]}]
set_property PACKAGE_PIN Y16 [get_ports {in2[3]}]
set_property PACKAGE_PIN K19 [get_ports {in2[2]}]
set_property PACKAGE_PIN P16 [get_ports {in2[1]}]
set_property PACKAGE_PIN K18 [get_ports {in2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in2[0]}]
set_property PACKAGE_PIN D18 [get_ports {out_r[3]}]
set_property PACKAGE_PIN G14 [get_ports {out_r[2]}]
set_property PACKAGE_PIN M15 [get_ports {out_r[1]}]
set_property PACKAGE_PIN M14 [get_ports {out_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ap_ready]
set_property IOSTANDARD LVCMOS33 [get_ports ap_start]
set_property IOSTANDARD LVCMOS33 [get_ports out_r_ap_vld]


set_property PACKAGE_PIN T19 [get_ports ap_start]
set_property PACKAGE_PIN P18 [get_ports out_r_ap_vld]
